name: check

on:
  workflow_call:
    inputs:
      R-version:
        required: true
        type: string
      make-grouping:
        required: true
        type: string

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2
  PGHOST: postgres
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_COMPILATION_FLAGS_KNOWN_: -Wformat -Werror=format-security -Wdate-time
      _R_CHECK_SYSTEM_CLOCK_: 0

    container: 
      image: pecan/depends:develop-R${{ inputs.R-version }}

    steps:
    - name: Work around checkout issues
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    
    - uses: actions/checkout@v4
      with:
        set-safe-directory: false

    - name: Check for filenames with spaces
      run: |
        SPACENAMES=`find . -name '* *'`
        if [ -n "$SPACENAMES" ]; then
          echo "::error file=${SPACENAMES}::Spaces in filename(s): ${SPACENAMES}. Please rename these files by converting spaces to underscores."
          exit 1
        fi

    - name: Install necessary tools
      run: apt-get update && apt-get install -y postgresql-client qpdf

    - name: Install R dependencies
      run: Rscript scripts/generate_dependencies.R && cd docker/depends && Rscript pecan.depends.R

    # Run PEcAn package checks with increased verbosity
    - name: Run check
      run: make -j1 VERBOSE=1 ${{ inputs.make-grouping }}
      env:
        REBUILD_DOCS: "FALSE"
        RUN_TESTS: "FALSE"

    # Run vignette separately to isolate issues
    - name: Run vignette separately with debugging
      run: |
        echo "Starting vignette check at $(date)"
        Rscript -e 'devtools::build_vignettes()'
        echo "Finished vignette check at $(date)"

    - name: Check for out-of-date files
      uses: infotroph/tree-is-clean@v1
